-- Add default_amount column to foods table
ALTER TABLE foods ADD COLUMN IF NOT EXISTS default_amount INTEGER DEFAULT 100;

-- Update common foods with realistic portion sizes
UPDATE foods SET default_amount = 60  WHERE name_he = 'ביצה שלמה';
UPDATE foods SET default_amount = 35  WHERE name_he = 'חלבון ביצה';
UPDATE foods SET default_amount = 50  WHERE name_he = 'לחמנייה';
UPDATE foods SET default_amount = 30  WHERE name_he = 'לחם לבן';
UPDATE foods SET default_amount = 30  WHERE name_he = 'לחם מחיטה מלאה';
UPDATE foods SET default_amount = 60  WHERE name_he = 'פיתה';
UPDATE foods SET default_amount = 150 WHERE name_he = 'חזה עוף';
UPDATE foods SET default_amount = 150 WHERE name_he = 'שוק עוף';
UPDATE foods SET default_amount = 150 WHERE name_he = 'כנפיים עוף';
UPDATE foods SET default_amount = 150 WHERE name_he = 'הודו חזה';
UPDATE foods SET default_amount = 150 WHERE name_he = 'בשר בקר טחון';
UPDATE foods SET default_amount = 200 WHERE name_he = 'סטייק';
UPDATE foods SET default_amount = 150 WHERE name_he = 'סלמון';
UPDATE foods SET default_amount = 120 WHERE name_he = 'טונה (שימורים)';
UPDATE foods SET default_amount = 150 WHERE name_he = 'דג לבן';
UPDATE foods SET default_amount = 200 WHERE name_he = 'אורז לבן מבושל';
UPDATE foods SET default_amount = 200 WHERE name_he = 'אורז חום מבושל';
UPDATE foods SET default_amount = 200 WHERE name_he = 'פסטה מבושלת';
UPDATE foods SET default_amount = 200 WHERE name_he = 'קוסקוס מבושל';
UPDATE foods SET default_amount = 200 WHERE name_he = 'קינואה מבושלת';
UPDATE foods SET default_amount = 80  WHERE name_he = 'שיבולת שועל';
UPDATE foods SET default_amount = 250 WHERE name_he = 'יוגורט 3%';
UPDATE foods SET default_amount = 250 WHERE name_he = 'יוגורט יווני';
UPDATE foods SET default_amount = 200 WHERE name_he = 'גבינה לבנה 5%';
UPDATE foods SET default_amount = 250 WHERE name_he = 'קוטג׳';
UPDATE foods SET default_amount = 30  WHERE name_he = 'גבינה צהובה';
UPDATE foods SET default_amount = 250 WHERE name_he = 'חלב 3%';
UPDATE foods SET default_amount = 10  WHERE name_he = 'חמאה';
UPDATE foods SET default_amount = 15  WHERE name_he = 'שמן זית';
UPDATE foods SET default_amount = 15  WHERE name_he = 'שמן קוקוס';
UPDATE foods SET default_amount = 20  WHERE name_he = 'טחינה';
UPDATE foods SET default_amount = 30  WHERE name_he = 'חמאת בוטנים';
UPDATE foods SET default_amount = 30  WHERE name_he = 'שקדים';
UPDATE foods SET default_amount = 30  WHERE name_he = 'אגוז מלך';
UPDATE foods SET default_amount = 30  WHERE name_he = 'קשיו';
UPDATE foods SET default_amount = 30  WHERE name_he = 'בוטנים';
UPDATE foods SET default_amount = 180 WHERE name_he = 'תפוח';
UPDATE foods SET default_amount = 120 WHERE name_he = 'בננה';
UPDATE foods SET default_amount = 180 WHERE name_he = 'תפוז';
UPDATE foods SET default_amount = 300 WHERE name_he = 'אבטיח';
UPDATE foods SET default_amount = 150 WHERE name_he = 'ענבים';
UPDATE foods SET default_amount = 80  WHERE name_he = 'מנגו';
UPDATE foods SET default_amount = 200 WHERE name_he = 'בטטה מבושלת';
UPDATE foods SET default_amount = 200 WHERE name_he = 'תפוח אדמה מבושל';
UPDATE foods SET default_amount = 200 WHERE name_he = 'תירס מבושל';
UPDATE foods SET default_amount = 150 WHERE name_he = 'עדשים מבושלות';
UPDATE foods SET default_amount = 150 WHERE name_he = 'חומוס מבושל';
UPDATE foods SET default_amount = 50  WHERE name_he = 'חומוס (ממרח)';
UPDATE foods SET default_amount = 100 WHERE name_he = 'פלאפל';
UPDATE foods SET default_amount = 30  WHERE name_he = 'אבקת חלבון';
UPDATE foods SET default_amount = 60  WHERE name_he = 'בר חלבון';
UPDATE foods SET default_amount = 20  WHERE name_he = 'דבש';
UPDATE foods SET default_amount = 40  WHERE name_he = 'שוקולד מריר';
